var darkImg = function(isDark){
	if(isDark.matches){
		$("#dAcc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/account (dark).svg");
		$("#dAgen").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/agenda (dark).svg");
		$("#dCal").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/calendar (dark).svg");
		$("#dCapp").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/cappex (dark).png");
		$("#dClos").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/close (dark).svg");
		$("#dColl").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/college (dark).svg");
		$("#dDrop").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/dropDown (dark).svg");
		$("#dHome").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/home (dark).svg");
		$("#dMont").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/mclinc (dark).png");
		$("#dNut").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/nutrislice (dark).png");
		$("#dPass").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/password (dark).svg");
		$("#dSafarl").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/safariMontage (dark).png");
		$("#dSched").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/schedule (dark).svg");
		$("#dSchoo").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/school (dark).svg");
		$("#dDirect").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/staffDirect (dark).svg");
		$("#dIsle").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/studyIsland (dark).png");
		$("#dTed").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/ted (dark).png");
		$("#dDisc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/discovery%20(dark).png");
		$("#dMan").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/Mango%20(dark).png");
		$("#dVec").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/Vectary%20(dark).png");
		$("#dCam").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@e2fa418/3DCam%20(dark).png");
		$("#dWork").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@e2fa418/work%20(dark).png");
	} else{
		$("#dAcc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/account.svg");
		$("#dAgen").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/agenda.svg");
		$("#dCal").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/calendar.svg");
		$("#dCapp").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/cappex.png");
		$("#dClos").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/close.svg");
		$("#dColl").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/college.svg");
		$("#dDrop").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/dropDown.svg");
		$("#dHome").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/home.svg");
		$("#dMont").attr("src", "https://media-exp1.licdn.com/dms/image/C560BAQH22RB56LFQ0Q/company-logo_200_200/0?e=2159024400&v=beta&t=MEc7C2RoVmMhyA7DSU-hkq1GVf3Y8uUfu5A_15q4nQ8");
		$("#dNut").attr("src", "https://lh3.googleusercontent.com/cKgJk0KvCWgnApH_qWB-y6LsKANJf46TvQfsvItubfgXv82v8MUZrd7k6eu28IXV5t8=s180-rw");
		$("#dPass").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/password.svg");
		$("#dSafarl").attr("src", "https://pbs.twimg.com/profile_images/890279088941920256/bOBWjDEL_400x400.jpg");
		$("#dSched").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/schedule.svg");
		$("#dSchoo").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/school.svg");
		$("#dDirect").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/staffDirect.svg");
		$("#dIsle").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/studyIsland.png");
		$("#dTed").attr("src", "https://lh3.googleusercontent.com/w_bxOqm2p2BntxtMt_MQqwxRJhI4MQR0cu-Gn_oKkd9UXGG3FH8S2xRTkx9vtArBcp8l=s180-rw");
		$("#dDisc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/discovery.png");
		$("#dMan").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/Mango.png");
		$("#dVec").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@d466db6/Vectary.png");
		$("#dCam").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@e2fa418/3DCam.png");
		$("#dWork").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@e2fa418/work.png");
	};
};
