var darkImg = function(isDark){
	if(isDark.matches){
		$("#dAcc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/account (dark).svg");
		$("#dAgen").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/agenda (dark).svg");
		$("#dCal").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/calendar (dark).svg");
		$("#dCapp").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/cappex (dark).png");
		$("#dClos").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/close (dark).svg");
		$("#dColl").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/college (dark).svg");
		$("#dDrop").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/dropDown (dark).svg");
		$("#dBay").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/ebay (dark).png");
		$("#dHist").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/history (dark).png");
		$("#dHome").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/home (dark).svg");
		$("#dInde").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/indeed (dark).png");
		$("#dLink").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/linkedinLearn (dark).png");
		$("#dMont").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/mclinc (dark).png");
		$("#dMon").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/money (dark).svg");
		$("#dNut").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/nutrislice (dark).png");
		$("#dPass").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/password (dark).svg");
		$("#dPal").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/payPal (dark).png");
		$("#dSafarl").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/safariMontage (dark).png");
		$("#dSched").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/schedule (dark).svg");
		$("#dSchoo").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/school (dark).svg");
		$("#dDirect").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/staffDirect (dark).svg");
		$("#dIsle").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/studyIsland (dark).png");
		$("#dTed").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/ted (dark).png");
		$("#dDisc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@220ee6e/discovery%20(dark).png");
		$("#dMan").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@ca28682/Mango%20(dark).png");
		$("#dVec").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@5024bb5/Vectary%20(dark).png");
	} else{
		$("#dAcc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/account.svg");
		$("#dAgen").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/agenda.svg");
		$("#dCal").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/calendar.svg");
		$("#dCapp").attr("src", "https://pbs.twimg.com/profile_images/1241088771002638337/xuXdZN2A_400x400.png");
		$("#dClos").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/close.svg");
		$("#dColl").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/college.svg");
		$("#dDrop").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/dropDown.svg");
		$("#dBay").attr("src", "https://lh3.googleusercontent.com/31-mJUIynIfQBizOn-w1yWLKHBxVeRKA3gz348_E3K-TnuEaqCjn_-Fr9j0yQ6i0y5E=s180-rw");
		$("#dHist").attr("src", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/History_Logo.svg/800px-History_Logo.svg.png");
		$("#dHome").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/home.svg");
		$("#dInde").attr("src", "https://lh3.googleusercontent.com/jj2z8DZ-Z5rV-Y4IY0ZklkuPjCchjeeisflFD0dU_zlJNpbUJkDTQpAMlc5rwutKFSU=s180-rw");
		$("#dLink").attr("src", "https://lh3.googleusercontent.com/_rscxiBBXosch987Y2RJjgeVzhCoewK_0IXsrIKFKKVAaXRqZaVXcSgap7uwM4-fbck=s180-rw");
		$("#dMont").attr("src", "https://media-exp1.licdn.com/dms/image/C560BAQH22RB56LFQ0Q/company-logo_200_200/0?e=2159024400&v=beta&t=MEc7C2RoVmMhyA7DSU-hkq1GVf3Y8uUfu5A_15q4nQ8");
		$("#dMon").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/money.svg");
		$("#dNut").attr("src", "https://lh3.googleusercontent.com/cKgJk0KvCWgnApH_qWB-y6LsKANJf46TvQfsvItubfgXv82v8MUZrd7k6eu28IXV5t8=s180-rw");
		$("#dPass").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/password.svg");
		$("#dPal").attr("src", "https://pbs.twimg.com/profile_images/1278352097688182784/Bn7-mEJ9_400x400.jpg");
		$("#dSafarl").attr("src", "https://pbs.twimg.com/profile_images/890279088941920256/bOBWjDEL_400x400.jpg");
		$("#dSched").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/schedule.svg");
		$("#dSchoo").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/school.svg");
		$("#dDirect").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/staffDirect.svg");
		$("#dIsle").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@f9a14c5/studyIsland.png");
		$("#dTed").attr("src", "https://lh3.googleusercontent.com/w_bxOqm2p2BntxtMt_MQqwxRJhI4MQR0cu-Gn_oKkd9UXGG3FH8S2xRTkx9vtArBcp8l=s180-rw");
		$("#dDisc").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@220ee6e/discovery.png");
		$("#dMan").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@ca28682/Mango.png");
		$("#dVec").attr("src", "https://cdn.jsdelivr.net/gh/shwin320/OneLocker@5024bb5/Vectary.png");
	};
};
